name: Rust Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ '**' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
    - name: Install minimal stable
      uses: dtolnay/rust-toolchain@stable 
    - uses: actions/checkout@v3
    - uses: Swatinem/rust-cache@v2
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install nextest
      uses: taiki-e/install-action@nextest
    - name: Build and run tests
      id: nextest
      # Profile "ci" is configured in .config/nextest.toml
      run: |
        echo "output=$(cargo nextest run --workspace --retries 2)" >> "$GITHUB_ENV"
        echo "$output"
        echo "last-line=$(tail -n 1 $output)" >> "$GITHUB_ENV"
        echo "last-line=$last-line" >> "$GITHUB_OUTPUT"
        echo "last-line-last-item=$(awk '{print $NF}' $last_line)" >> "$GITHUB_OUTPUT"

    - name: Create issue for flaky tests
      if: ${{ contains(steps.nextest.outputs.last-line, 'FLAKY') }}
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TEST_NAME: ${{ steps.nextest.outputs.last-line-last-item }}
        OS: ${{ matrix.os }}
      with:
        filename: .github/ISSUE_TEMPLATE/flaky_test_report.md
        update_existing: true
        

